[workspace]
members = [
    "crates/regen-client",
    "crates/regen-types", 
    "crates/regen-modules",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/https://github.com/ybird-labs/regen-rs"
authors = ["Jeancarlo Barrios "]

[workspace.dependencies]
# Core async runtime - latest stable version
tokio = { version = "1.46", features = ["macros", "rt-multi-thread"] }
async-trait = "0.1"

thiserror = "2.0"
anyhow = "1.0"

serde = { version = "1.0", features = ["derive"] }

