[package]
name = "proto-compiler"
version = "0.1.0"
edition = "2021"

# Keep this out of the workspace
[workspace]

[dependencies]
prost-build = "0.13"
tonic-build = "0.13"
walkdir = "2.5"
anyhow = "1.0"
clap = { version = "4.0", features = ["derive"] }