name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  checks:
    name: Nix Flake Checks
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        check:
          - fmt
          - clippy
          - doc
          - audit
          - outdated
          - tests
          - build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Nix
      uses: cachix/install-nix-action@v29
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          
    - name: Setup Nix cache
      uses: cachix/cachix-action@v15
      with:
        name: devenv
        
    - name: Run ${{ matrix.check }} check
      run: |
        case "${{ matrix.check }}" in
          fmt)
            nix run .#format
            ;;
          clippy)
            nix run .#lint
            ;;
          build)
            nix run .#build
            ;;
          tests)
            nix run .#test
            ;;
          audit)
            nix run .#audit
            ;;
          doc)
            nix develop --command cargo doc --all-features --no-deps
            ;;
          outdated)
            nix develop --command cargo outdated || true
            ;;
        esac

  flake-check:
    name: Validate Nix Flake
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Nix
      uses: cachix/install-nix-action@v29
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          
    - name: Check flake
      run: nix flake check -L

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Nix
      uses: cachix/install-nix-action@v29
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          
    - name: Setup Nix cache
      uses: cachix/cachix-action@v15
      with:
        name: devenv
        
    - name: Run integration tests
      run: nix run .#test-ignored -L